// Central definition of every enum-ish value in the schema.
// SQLite has no native enums, so these lists are the single source of truth and
// are used by both the zod validation layer and the UI select inputs.

export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  SOCIETY_ADMIN: "SOCIETY_ADMIN",
  RESIDENT: "RESIDENT",
};

export const USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};

export const SOCIETY_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};

export const FLAT_STATUS = {
  OCCUPIED: "OCCUPIED",
  VACANT: "VACANT",
};

export const RESIDENT_TYPE = {
  OWNER: "OWNER",
  TENANT: "TENANT",
};

export const CALCULATION_TYPE = {
  FIXED: "FIXED",
  PER_SQFT: "PER_SQFT",
  FLAT_TYPE: "FLAT_TYPE",
};

export const FREQUENCY = {
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  ANNUAL: "ANNUAL",
  ONE_TIME: "ONE_TIME",
};

export const CHARGE_TYPE = {
  MAINTENANCE: "MAINTENANCE",
  PARKING: "PARKING",
  WATER: "WATER",
  SINKING_FUND: "SINKING_FUND",
  SPECIAL_FUND: "SPECIAL_FUND",
  OTHER: "OTHER",
};

export const INVOICE_STATUS = {
  PENDING: "PENDING",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  PAID: "PAID",
  OVERDUE: "OVERDUE",
  CANCELLED: "CANCELLED",
};

export const PAYMENT_METHOD = {
  CASH: "CASH",
  CHEQUE: "CHEQUE",
  BANK_TRANSFER: "BANK_TRANSFER",
  UPI: "UPI",
  RAZORPAY: "RAZORPAY",
  // Simulated gateway. Never real money, so it is labelled as its own method
  // rather than being filed under RAZORPAY - a demo run must not look like a
  // genuine collection in the books.
  MOCK: "MOCK",
  OTHER: "OTHER",
};

/** Manual methods an admin can record directly. Online ones arrive via a gateway. */
export const OFFLINE_PAYMENT_METHODS = [
  PAYMENT_METHOD.CASH,
  PAYMENT_METHOD.CHEQUE,
  PAYMENT_METHOD.BANK_TRANSFER,
  PAYMENT_METHOD.UPI,
  PAYMENT_METHOD.OTHER,
];

export const COMPLAINT_CATEGORY = {
  PLUMBING: "PLUMBING",
  ELECTRICAL: "ELECTRICAL",
  CLEANLINESS: "CLEANLINESS",
  PARKING: "PARKING",
  SECURITY: "SECURITY",
  NOISE: "NOISE",
  WATER: "WATER",
  OTHER: "OTHER",
};

export const COMPLAINT_PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  URGENT: "URGENT",
};

export const COMPLAINT_STATUS = {
  OPEN: "OPEN",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
  REOPENED: "REOPENED",
};

export const NOTICE_CATEGORY = {
  GENERAL: "GENERAL",
  URGENT: "URGENT",
  MAINTENANCE: "MAINTENANCE",
  EVENT: "EVENT",
  MEETING: "MEETING",
};

export const NOTICE_STATUS = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
};

export const AUDIT_ACTION = {
  SOCIETY_CREATED: "SOCIETY_CREATED",
  SOCIETY_UPDATED: "SOCIETY_UPDATED",
  FLAT_CREATED: "FLAT_CREATED",
  FLAT_UPDATED: "FLAT_UPDATED",
  FLAT_DELETED: "FLAT_DELETED",
  RESIDENT_CREATED: "RESIDENT_CREATED",
  RESIDENT_UPDATED: "RESIDENT_UPDATED",
  RESIDENT_IMPORTED: "RESIDENT_IMPORTED",
  FEE_CONFIG_CREATED: "FEE_CONFIG_CREATED",
  FEE_CONFIG_UPDATED: "FEE_CONFIG_UPDATED",
  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_UPDATED: "INVOICE_UPDATED",
  INVOICE_CANCELLED: "INVOICE_CANCELLED",
  PAYMENT_RECORDED: "PAYMENT_RECORDED",
  PAYMENT_UPDATED: "PAYMENT_UPDATED",
  PAYMENT_DELETED: "PAYMENT_DELETED",
  RECEIPT_GENERATED: "RECEIPT_GENERATED",
  COMPLAINT_CREATED: "COMPLAINT_CREATED",
  COMPLAINT_UPDATED: "COMPLAINT_UPDATED",
  COMPLAINT_STATUS_CHANGED: "COMPLAINT_STATUS_CHANGED",
  COMPLAINT_ASSIGNED: "COMPLAINT_ASSIGNED",
  NOTICE_CREATED: "NOTICE_CREATED",
  NOTICE_UPDATED: "NOTICE_UPDATED",
  NOTICE_DELETED: "NOTICE_DELETED",
};

// Allowed complaint status transitions (section 26 of the spec).
export const COMPLAINT_TRANSITIONS = {
  OPEN: ["ASSIGNED", "IN_PROGRESS", "RESOLVED", "CLOSED"],
  ASSIGNED: ["IN_PROGRESS", "RESOLVED", "CLOSED"],
  IN_PROGRESS: ["RESOLVED", "CLOSED"],
  RESOLVED: ["CLOSED", "REOPENED"],
  CLOSED: ["REOPENED"],
  REOPENED: ["ASSIGNED", "IN_PROGRESS", "RESOLVED", "CLOSED"],
};